#! /bin/sh


vfile=`dirname $0`/VERSIONS
if [ ! -r ${vfile} ] ; then
  echo VERSIONS file not found
  exit 1
fi

source ${vfile}

start=`date`
echo Started at: ${start}

tests=-T

bsp=

exitStatus=0
for cpu in $*
do
  case $cpu in
    native)  bsp=native       ;;
    arm)     bsp=edb7312      ;;
    avr)     bsp=avrtest      ;;
    bfin)    bsp=eZKit533     ;;
    h8300)   bsp=h8sim        ;;
    i386)    bsp=pc386        ;;
    m32c)    bsp=m32csim      ;;
    m32r)    bsp=m32rsim      ;;
    m68k)    bsp=mcf5206elite ;;
    mips)    bsp=jmr3904      ;;
    powerpc) bsp=psim         ;;
    sh)      bsp=simsh1       ;;
    sparc)   bsp=sis          ;;
    *)
      echo "Unknown CPU ${cpu}"
      exit 1
      ;;
  esac

  doOne=${SCRIPTDIR}/do_one 
  echo Building tools for ${cpu} and testing on ${bsp} ... 
  if [ ${cpu} = "native" ] ; then
    time sh -x ${doOne} -n >native.log 2>&1
    if [ $? -ne 0 ] ; then
      echo NATIVE FAILED!!! BAILING
      exitStatus=1
      break
    fi
  else
    # Everything
    time sh -x ${doOne} -v -A ${tests} ${cpu} ${bsp} >${bsp}.log 2>&1
    # Just C
    #time sh -x ${doOne} -v -b -D -1 -r ${tests} ${cpu} ${bsp} >${bsp}.log 2>&1
    # Just C/C++
    #time sh -x ${doOne} -v -1 -r -g ${tests} ${cpu} ${bsp} >${bsp}.log 2>&1
  fi
  echo $?
done


stopped=`date`
echo Started at: ${start}
echo Stopped at: ${stopped}
exit $exitStatus
