#! /bin/sh
#
#  Test Driver
#
#  $Id$
#

vfile=`dirname $0`/VERSIONS
if [ ! -r ${vfile} ] ; then
  echo VERSIONS file not found
  exit 1
fi

source ${vfile}

if [ ! -d ${BASEDIR} ] ; then
  echo Have you set the BASEDIR in VERSIONS correctly?
  exit 1
fi

start=`date`
echo Started at: ${start}

BASEDIR=`pwd`

# HELPER - Update RTEMS
update_rtems()
{
  cd ${RTEMSDIR}
  cvs up -Pd 2>&1 | grep -v ^cvs
  ./bootstrap -c
  ./bootstrap
}

# HELPER - Update GCC
update_gcc()
{
  cd ${GCCDIR}
  ./contrib/gcc_update
}

# HELPER - Remove all the installed previous builds
clean_up()
{
  rm -rf install/* &
  rm -rf bsp-install/* &
  wait
}

install_auto()
{
  for auto in ${AUTOCONF} ${AUTOMAKE}
  do
    if [ ! -d ${auto} ] ; then
      echo "${d} not installed"
      exit 0
    fi
    cd ${auto}
    make distclean
    ./configure --prefix=${BASEDIR}/install
    make all install
  done
}

# This handles GNU tools from CVS
update_others()
{
  for d in ${BINUTILSDIR} ${GDBDIR} ${NEWLIBDIR}
  do
    
    if [ ! -d ${d} ] ; then
      echo "Cannot locate ${d} -- aborting"
      exit 1
    fi

    case ${d} in
      *cvs*)
        cd ${d}
	cvs up -P 2>&1 | grep -v ^cvs
        ;;
      *)
        ;;
    esac
  done
}

do_cpus()
{
  start=`date`
  echo Started at: ${start}

  tests=-T

  bsp=

  exitStatus=0
  for cpu in $*
  do
    case $cpu in
      native)  bsp=native       ;;
      arm)     bsp=edb7312      ;;
      avr)     bsp=avrtest      ;;
      bfin)    bsp=eZKit533     ;;
      h8300)   bsp=h8sim        ;;
      i386)    bsp=pc386        ;;
      m32c)    bsp=m32csim      ;;
      m32r)    bsp=m32rsim      ;;
      m68k)    bsp=mcf5206elite ;;
      mips)    bsp=jmr3904      ;;
      powerpc) bsp=psim         ;;
      sh)      bsp=simsh1       ;;
      sparc)   bsp=sis          ;;
      *)
	echo "Unknown CPU ${cpu}"
	exit 1
	;;
    esac

    doOne=${SCRIPTDIR}/do_one 
    # Everything
    time sh -x ${doOne} -v -d -A ${tests} ${cpu} ${bsp} >${bsp}.log 2>&1
    # Just C
    #time sh -x ${doOne} -v -b -D -1 -r ${tests} ${cpu} ${bsp} >${bsp}.log 2>&1
    # Just C/C++
    #time sh -x ${doOne} -v -1 -r -g ${tests} ${cpu} ${bsp} >${bsp}.log 2>&1
    echo $?
  done


  stopped=`date`
  echo Started at: ${start}
  echo Stopped at: ${stopped}
}

# Clean the install point
clean_up

# Update gcc and install autotools in parallel
install_auto &
update_gcc &
update_others &
wait

# Do any remaining prep work in parallel
update_rtems &
wait

# Build the native compiler as a baseline to build the others
time sh -x ${SCRIPTDIR}/do_one -n >native.log 2>&1

# Now cycle over all these CPUs
if [ $? -eq 0 ] ; then
  do_cpus powerpc sh sparc
  #${SCRIPTDIR}/do_cpus m32c arm h8300 i386 mips sh powerpc sparc
  #${SCRIPTDIR}/do_cpus i386 
  # wait
fi
# ${SCRIPTDIR}/do_cpus sparc powerpc mips i386 arm

stopped=`date`
echo Started at: ${start}
echo Stopped at: ${stopped}
