#! /bin/bash
#
#  Run over all possible RTEMS configurations
#
#

fix_usercfg()
{
  tests_f=$1
  tcpip_f=$2
  posix_f=$3
  cxx_f=$4
  itron_f=$5
  rdbg_f=$6
  mp_f=$7
  inlines_f=$7

  cp user.cfg user.cfg.back

  sed -e "s/ENABLE_RTEMS_TESTS=.*$/ENABLE_RTEMS_TESTS=${tests_f}/" \
      -e "s/ENABLE_RTEMS_TCPIP=.*$/ENABLE_RTEMS_TCPIP=${tcpip_f}/" \
      -e "s/ENABLE_RTEMS_POSIX=.*$/ENABLE_RTEMS_POSIX=${posix_f}/" \
      -e "s/ENABLE_RTEMS_CXX=.*$/ENABLE_RTEMS_CXX=${cxx_f}/" \
      -e "s/ENABLE_RTEMS_ITRON=.*$/ENABLE_RTEMS_ITRON=${itron_f}/" \
      -e "s/ENABLE_RTEMS_RDBG=.*$/ENABLE_RTEMS_RDBG=${rdbg_f}/" \
      -e "s/ENABLE_RTEMS_MP=.*$/ENABLE_RTEMS_MP=${mp_f}/" \
      -e "s/DISABLE_INLINES=.*$/DISABLE_INLINES=${inlines_f}/" \
   <user.cfg.back >user.cfg
}


if [ $# -ne 2 ] ; then
  echo Usage: $0 target BSP
  exit 1
fi
target=$1
bsp=$2
start=`date`

for test_l in samples ; do   # note yes is left out
for tcpip_l in no yes ; do
for posix_l in no yes ; do
for itron_l in no yes ; do
for cxx_l in no yes ; do
for rdbg_l in no yes ; do
for mp_l in no yes ; do
  fix_usercfg $test_l $tcpip_l $posix_l $cxx_l $itron_l $rdbg_l $mp_l $inlines_l
  echo
  echo ===============================================
  echo
  echo Testing ...
  grep ^ENABLE user.cfg
  echo
  outf="log/ALLCONFS-${target}-${bsp}"
  outf="${outf}-${test_l}_tests-${tcpip_l}net-${posix_l}posix"
  outf="${outf}-${itron_l}itron-${cxx_l}cxx-${rdbg_l}rdbg"
  outf="${outf}-${mp_l}mp"
  outf=`echo ${outf} | sed -e 's/yes//g'`
  echo "./bit_rtems ${target} ${bsp} >${outf} 2>&1"
  ./bit_rtems ${target} ${bsp} >${outf} 2>&1
done # mp
done # rdbg
done # cxx
done # itron
done # posix
done # tcpip
done # test

stop=`date`

echo "Started:  " $start
echo "Finished: " $stop
exit 0



