#! /bin/bash
#
#

if [ -d log ] ; then
  logdir=log/
else
  logdir=
fi

while :
do
  for f in `ls -1 ${logdir}* | grep -v info$`
  do
    grep "END OF" $f >/dev/null
    if [ $? -ne 0 ] ; then
      echo "ERROR - $f did not appear to complete execution"
    fi
  done

  if [ X${1} = X ] ; then
    break
  fi
  sleep $1
  echo
done
exit 0
