#! /bin/sh
#
# Request a coverity run for RTEMS
#
# Send an email to build@submit.scan.coverity.com with the following contents:
#
#    VERSION;PROJECT;PASSWORD;MAILOPT;URL
#
#    VERSION:  The only supported version is v1 as described in this text.
#    PROJECT:  The name of your project, as registered with Scan.
#    PASSWORD: The password for build submissions for your project,
#              as arranged with the Scan admin staff
#    MAILOPT:  Either MAIL, NOMAIL, or an email address.

cat <<EOF |
v1;RTEMS;ce5hazuV;joel@oarcorp.com;http://www.rtems.org/ftp/private/coverity/project.tgz
EOF
mail -u joel -r joel@oarcorp.com -s "RTEMS Coverity Run Request"  build@submit.scan.coverity.com 
exit 0
