#! /bin/sh
#
#

if [ $# -lt 2 ] ; then
  echo USAGE: BSP COMPILER
  exit 1
fi

vfile=`dirname $0`/../VERSIONS
if [ ! -r ${vfile} ] ; then
  echo VERSIONS file not found
  exit 1
fi

source ${vfile}

case $1 in
  eZKit533) 
    CPU=bfin
    BSP=eZKit533
    DEJABSP=nosim
    BSP_SIM=nosim
    ;;
  edb7312) 
    CPU=arm
    BSP=edb7312
    DEJABSP=edb7312
    BSP_SIM=edb7312
    ;;
  lm32_evr) 
    CPU=lm32
    BSP=lm32_evr
    DEJABSP=lm32_evr
    BSP_SIM=lm32_evr
    ;;
  m32csim) 
    CPU=m32c
    BSP=m32csim
    DEJABSP=m32csim
    BSP_SIM=m32csim
    ;;
  m32rsim) 
    CPU=m32r
    BSP=m32rsim
    DEJABSP=m32rsim
    BSP_SIM=m32rsim
    ;;
  mcf5206elite) 
    CPU=m68k
    BSP=mcf5206elite
    DEJABSP=nosim
    BSP_SIM=nosim
    ;;
  uC5282) 
    CPU=m68k
    BSP=uC5282
    DEJABSP=uC5282
    BSP_SIM=uC5282
    ;;
  h8sim) 
    CPU=h8300
    BSP=h8sim
    DEJABSP=h8sim
    BSP_SIM=h8sim
    ;;
  simsh1) 
    CPU=sh
    BSP=simsh1
    DEJABSP=simsh1
    BSP_SIM=simsh
    ;;
  jmr3904) 
    CPU=mips
    BSP=jmr3904
    DEJABSP=jmr3904
    BSP_SIM=jmr3904
    ;;
  sis) 
    CPU=sparc
    BSP=sis
    DEJABSP=sis
    BSP_SIM=sis
    ;;
  psim)
    CPU=powerpc
    BSP=psim
    DEJABSP=psim
    BSP_SIM=psim
    ;;
  qemuppc) 
    CPU=powerpc
    BSP=qemuppc
    DEJABSP=qemuppc
    BSP_SIM=qemuppc
    ;;
  qemu|pc386)
    CPU=i386
    BSP=pc386
    DEJABSP=qemu
    BSP_SIM=pc386
    ;;
  *)
    echo UNKNOWN BSP
    exit 1
    ;;
esac

rtemsdir=${BSP_INSTALL}/${CPU}-rtems${RTEMS_VERSION}/${BSP}

dfile=~/.dejagnurc
if [ -r ${dfile} ] ; then
  sed -e "s,^set boards_dir.*$,set boards_dir ${SCRIPTDIR}/dejagnu/boards," \
     <${dfile} >XXX
  mv XXX ${dfile}
else
  echo "set boards_dir ${SCRIPTDIR}/dejagnu/boards" >${dfile}
fi

case $2 in
  libgo)
    rtems_libgo_init=${SCRIPTDIR}/gcc/rtems_libgo_init.c
    rtems_bin2c=${INSTALL}/bin/rtems-bin2c
    make check-target-libgo RUNTESTFLAGS="\
    SIM=${BSP_SIM} \
    RTEMS_MAKEFILE_PATH=${rtemsdir} \
    RTEMS_LIBGO_INIT=${rtems_libgo_init} \
    RTEMS_BIN2C=${rtems_bin2c} \
    RTEMS_CONFIG_OBJ= \
    --target_board=rtems-${CPU}-${DEJABSP} \
    "
    ;;
  gccgo)
    RTEMS_MAKEFILE_PATH=${rtemsdir} \
    SCRIPTDIR=${SCRIPTDIR} \
      make -f ${SCRIPTDIR}/gcc/Makefile.rtems_gccgoinit
    if [ $? -ne 0 ] ; then
      echo unable to compile RTEMS GCC Go Init File
      exit 1
    fi
    rtems_config=`pwd`/rtems_gccgo_init.o
    make check-go RUNTESTFLAGS="\
    SIM=${BSP_SIM} \
    RTEMS_MAKEFILE_PATH=${rtemsdir} \
    RTEMS_CONFIG_OBJ=${rtems_config} \
    --target_board=rtems-${CPU}-${DEJABSP} \
    "
    ;;
  objc)
    RTEMS_MAKEFILE_PATH=${rtemsdir} \
    SCRIPTDIR=${SCRIPTDIR} \
      make -f ${SCRIPTDIR}/gcc/Makefile.rtems_gccmain
    if [ $? -ne 0 ] ; then
      echo unable to compile RTEMS GCC Main
      exit 1
    fi
    rtems_config=`pwd`/rtems_gcc_main.o
    make check-objc RUNTESTFLAGS="\
    SIM=${BSP_SIM} \
    RTEMS_MAKEFILE_PATH=${rtemsdir} \
    RTEMS_CONFIG_OBJ=${rtems_config} \
    --target_board=rtems-${CPU}-${DEJABSP} \
    "
    ;;
  libjava)
    RTEMS_MAKEFILE_PATH=${rtemsdir} \
    SCRIPTDIR=${SCRIPTDIR} \
      make -f ${SCRIPTDIR}/gcc/Makefile.rtems_gcjinit
    if [ $? -ne 0 ] ; then
      echo unable to compile RTEMS GCC Java Init File
      exit 1
    fi
    rtems_config=`pwd`/rtems_gcj_init.o
    make check-gcc-java RUNTESTFLAGS="\
    SIM=${BSP_SIM} \
    RTEMS_MAKEFILE_PATH=${rtemsdir} \
    RTEMS_CONFIG_OBJ=${rtems_config} \
    --target_board=rtems-${CPU}-${DEJABSP} \
    "
    ;;
  gcc)
    RTEMS_MAKEFILE_PATH=${rtemsdir} \
    SCRIPTDIR=${SCRIPTDIR} \
      make -f ${SCRIPTDIR}/gcc/Makefile.rtems_gccmain
    if [ $? -ne 0 ] ; then
      echo unable to compile RTEMS GCC Main
      exit 1
    fi
    rtems_config=`pwd`/rtems_gcc_main.o
    make check-gcc RUNTESTFLAGS="\
    SIM=${BSP_SIM} \
    RTEMS_MAKEFILE_PATH=${rtemsdir} \
    RTEMS_CONFIG_OBJ=${rtems_config} \
    --target_board=rtems-${CPU}-${DEJABSP} \
    "
    ;;
  *)
    RTEMS_MAKEFILE_PATH=${rtemsdir} \
    SCRIPTDIR=${SCRIPTDIR} \
      make -f ${SCRIPTDIR}/gcc/Makefile.rtems_gccmain
    if [ $? -ne 0 ] ; then
      echo unable to compile RTEMS GCC Main
      exit 1
    fi
    rtems_config=`pwd`/rtems_gcc_main.o
    echo make check RUNTESTFLAGS="\
    SIM=${BSP_SIM} \
    RTEMS_MAKEFILE_PATH=${rtemsdir} \
    RTEMS_CONFIG_OBJ=${rtems_config} \
    --target_board=rtems-${CPU}-${DEJABSP} \
    "
exit 0
    ;;
esac

# "execute.exp=pr206*"
# vect.exp=vect*
# powerpc.exp=405*
