#! /bin/sh
#
#  $Id$
#

vfile=`dirname $0`/VERSIONS-COVERAGE
if [ ! -r ${vfile} ] ; then
  echo VERSIONS-COVERAGE file not found
  exit 1
fi

source ${vfile}

if [ ! -d ${BASEDIR} ] ; then
  echo Have you set the BASEDIR in VERSIONS correctly?
  exit 1
fi

progname=${0##*/}        # fast basename hack for ksh, bash

RUNCOVERAGE=${COVBASE}/run_coverage



BSPS="erc32 leon2 leon3"
case ${RTEMS_VERSION} in
  4.6)  ;;
  4.7)  ;;
  4.8)  ;;
  4.9)  BSPS="${BSPS} edb7312 smdk2410 pc386 uC5282"
        ;;
  4.10) BSPS="${BSPS} edb7312 gumstix smdk2410 pc386 uC5282 qemuppc"
        ;;
  *)
    echo "ERROR -- UNKNOWN RTEMS VERSION ${RTEMS_VERSION}"
    exit 1
    ;;
esac


${RUNCOVERAGE} -t update 
for b in ${BSPS}
do
  ${RUNCOVERAGE} -t ${b}_baseline
done
exit 0
