#! /bin/sh
#
#  $Id$

base=${HOME}/coverage

TARGET=sparc-rtems4.10
CPU=sparc
BSP=erc32

PWD=`pwd`
cd ${base}/${BSP}-tests 
test $? -eq 0 || exit 1

rm -f *.exe *.cov *.tmp
rm -rf log
rm -f annotated.dmp hello.num report

cd ../b-${BSP}
test $? -eq 0 || exit 1

pwd
find . -name *.exe
cp `find . -name *.exe` ../${BSP}-tests

echo done
cd $PWD
exit 0
