#! /bin/sh
#
#  Script to perform a single coverage test run on a single BSP
#  in a specific configuration.  This script automates all steps
#  of building RTEMS, running the tests, and generating the reports.
#
#  $Id$
#

vfile=`dirname $0`/VERSIONS-COVERAGE
if [ ! -r ${vfile} ] ; then
  echo VERSIONS-COVERAGE file not found
  exit 1
fi

source ${vfile}

if [ ! -d ${BASEDIR} ] ; then
  echo Have you set the BASEDIR in VERSIONS correctly?
  exit 1
fi

progname=${0##*/}        # fast basename hack for ksh, bash

USAGE=\
"usage: $progname [ -opts ]
        -v        -- verbose (default=no)
        -A        -- Execute all steps (default=no)
        -B BSP    -- Specify BSP to test
        -P        -- Enable POSIX API (default=yes)
        -D        -- Enable Developmental Coverage (default=no)
        -S        -- Optimize for size (default=no)
        -m        -- Update and build covMerge (default=no)
        -u        -- Do CVS update on RTEMS (default=no)
        -c        -- Configure RTEMS (default=no)
        -b        -- Build RTEMS (default=no)
        -C        -- copy tests from build to test execution point (default=no)
        -r        -- run the tests (default=no)
        -R        -- generate a report (default=no)

Notes:  + There are currently NO checks at each step to determine if
          the previous steps were performed!!!
        + Use of each option toggles the setting.  For example, \"-v -v -A -u\"
          results in verbose=no and all steps done except CVS update on RTEMS.

"

#   log an error to stderr
prerr()
{
    echo "$*" >&2
}

fatal() {
    prerr "$USAGE"
    [ "$1" ] && (prerr ; prerr $*);
    exit 1
}

warn() {
    [ "$1" ] && prerr $*
}

check_status()
{
  if [ $1 -ne 0 ] ; then
    shift
    echo "FAILED: " "$*" >&2
    exit 1
  fi
}

toggle()
{
  case $1 in
    no)  echo "yes" ;;
    yes) echo "no" ;;
    *)   fatal "Unknown value to toggle ($1)" ;;
  esac
}

# parse arguments for these
verbose="no"
do_all="no"
do_posix="yes"
do_developmental="no"
do_optimize_size="no"
do_covmerge="no"
do_rtems_update="no"
do_rtems_configure="no"
do_rtems_build="no"
do_copy_tests="no"
do_run_tests="no"
do_report="no"
BSP="not_set"

while getopts vB:PDSmAucbCrR OPT
do
    case "$OPT" in
        A)
          do_all="yes"
          do_covmerge="yes"
          do_posix="yes"
          do_rtems_update="yes"
          do_rtems_configure="yes"
          do_rtems_build="yes"
          do_copy_tests="yes"
          do_run_tests="yes"
          do_report="yes"
          ;;
        B) BSP="${OPTARG}";;
        v) verbose=`toggle ${verbose}` ;;
        m) do_covmerge=`toggle ${do_covmerge}` ;;
        P) do_posix=`toggle ${do_posix}` ;;
        D) do_developmental=`toggle ${do_developmental}` ;;
        S) do_optimize_size=`toggle ${do_optimize_size}` ;;
        u) do_rtems_update=`toggle ${do_rtems_update}` ;;
        c) do_rtems_configure=`toggle ${do_rtems_configure}` ;;
        b) do_rtems_build=`toggle ${do_rtems_build}` ;;
        C) do_copy_tests=`toggle ${do_copy_tests}` ;;
        r) do_run_tests=`toggle ${do_run_tests}` ;;
        R) do_report=`toggle ${do_report}` ;;
        *) fatal;;
    esac
done

#  If we are to update or configure RTEMS, then we need to clean the
#  RTEMS build tree up.
do_clean="no"
if [ ${do_rtems_update} = "yes" -o \
     ${do_rtems_configure} = "yes" ] ; then
  do_clean="yes"
fi

# allow bsp override
if [ ${BSP} == "not_set" ] ; then
  fatal "No BSP selected"
fi

# For most BSPs, there is a script with the same name as the BSP.
RUNNER=${BSP}

case ${BSP} in
  pc386)
    CPU=i386
    RUNNER=qemu-rtems
    COVERAGE_FORMAT=RTEMS
    RTEMS_EXTRA_ARGS="USE_COM1_AS_CONSOLE=1"
    RTEMS_EXTRA_ARGS="${RTEMS_EXTRA_ARGS} BSP_PRESS_KEY_FOR_RESET=0"
    ;; 
  erc32|leon2|leon3)
    CPU=sparc
    COVERAGE_FORMAT=TSIM
    ;;
  edb7312|rtl22xx|gumstix|smdk2410)
    CPU=arm
    COVERAGE_FORMAT=Skyeye
    RTEMS_EXTRA_ARGS="ON_SKYEYE=1"
    ;;
  *)
    fatal "Unsupported BSP (${BSP}) for coverage analysis."
    ;;
esac

if [ ${RTEMS_VERSION} = 4.6 ] ; then
  TARGET=${CPU}-rtems
else
  TARGET=${CPU}-rtems${RTEMS_VERSION}
fi

##### VERBOSE
print_verbose()
{
  echo "BSP:                " ${BSP}
  echo "Target:             " ${TARGET}
  echo "do_all:             " ${do_all}
  echo "do_covmerge         " ${do_covmerge}
  echo "do_posix:           " ${do_posix}
  echo "do_developmental:   " ${do_developmental}
  echo "do_optimize_size:   " ${do_optimize_size}
  echo "do_rtems_update:    " ${do_rtems_update}
  echo "do_rtems_configure: " ${do_rtems_configure}
  echo "do_rtems_build:     " ${do_rtems_build}
  echo "do_copy_tests:      " ${do_copy_tests}
  echo "do_run_tests:       " ${do_run_tests}
  echo "do_report:          " ${do_report}
  echo "Clean Before:       " ${do_clean}
}

if [ ${verbose} = "yes" ] ; then
  print_verbose
fi

# Basic error checking and sanity checking on the directory structure
# and PATH
if [ ! -d ${COVBASE} ] ; then
  echo You do not have ${COVBASE}
  exit 1
fi

if [ ! -d ${RTEMSDIR} ] ; then
  echo "Check out RTEMS!!!"
  exit 1
fi

grep _COVERAGE ${RTEMSDIR}/c/src/make/leaf.cfg >/dev/null
if [ $? -ne 0 ] ; then
  echo "It doesn't look like you patched the RTEMS source for coverage."
  exit 1
fi

type ${TARGET}-gcc
check_status $? "Path appears to be broken"

# Start real action
NM=${TARGET}-nm
type ${NM}
check_status $? "Cannot find ${NM} on PATH"

if [ ${do_optimize_size} = yes ] ; then
 c_opt=-Os
else
 c_opt=-O2
fi

EXTENSION=${c_opt}
if [ ${do_posix} = yes ] ; then
  EXTENSION=${EXTENSION}P
else
  EXTENSION=${EXTENSION}p
fi

if [ ${do_developmental} = yes ] ; then
  EXTENSION=${EXTENSION}D
else
  EXTENSION=${EXTENSION}d
fi

day=`date +%Y%m%d`
hour=`date +%H`
minute=`date +%M`
results_dir=${BSP}${EXTENSION}-${day}-${hour}${minute}

echo "Testing ${TARGET}/${BSP} at optimization (${c_opt})"

# print a data element in table
print_element()
{
  echo "  <TD>"${*}"</TD>"
}

# generate table row of results in html
generate_html()
{
  echo "<TR>"
    print_element ${day}
    print_element ${hour}:${minute}
    print_element ${c_opt}
    print_element ${do_posix}
    print_element ${do_developmental}
    print_element `grep "uncovered range" summary.txt | cut -d ' ' -f1`
    print_element `grep "age Not Exec" summary.txt | cut -d ':' -f2`
    print_element `grep "age Exec" summary.txt | cut -d ':' -f2`
    print_element `grep "Bytes Not Exec" summary.txt | cut -d ':' -f2`
    print_element `grep "Bytes Analyzed" summary.txt | cut -d ':' -f2`
    print_element "<A HREF=\"${results_dir}\">untarred</A> " \
                  "<A HREF=\"${results_dir}.tar.bz2\">tarball</A> "
  echo "</TR>"
}

# generate the coverage report set
generate_report()
{
  if [ $# -ne 3 ] ; then
    echo Usage: ${0} TARGET BSP COVERAGE_FORMAT
    exit 1
  fi

  TARGET=${1}
  BSP=${2}
  COVERAGE_FORMAT=${3}

  cd ${BASEDIR}/${BSP}-tests/
  check_status $? "cd ${BSP}-tests"

  ${NM} -g -n hello.exe >hello.num

  # Basic validity checking
  tlow=`grep "T ${lowsym}$" hello.num | cut -d' ' -f1`
  if [ X${tlow} = X ] ; then
    echo "low symbol (${lowsym}) not found"
  fi
  thigh=`grep "T ${highsym}$" hello.num | cut -d' ' -f1`
  if [ X${thigh} = X ] ; then
    echo "high symbol (${highsym}) not found"
  fi

  if [ X${tlow} = X -o X${thigh} = X ] ; then
    echo "Did you patch RTEMS for coverage testing?"
    exit 1
  fi

  rm -f merged.cov report.txt

  check_endof                                             >summary.txt
  ${COVBASE}/covmerge \
    -l 0x${tlow} -h 0x${thigh} \
    -r report.txt -s sizes.txt \
    -E ${COVBASE}/Explanations.txt \
    -f ${COVERAGE_FORMAT} \
    -T ${TARGET} -e hello.exe -m merged.cov *.cov        >>summary.txt
  check_status $? "covmerge failed"

  (echo "====== Largest Range Sizes (Size and Count)======" ; \
    grep ^Size report.txt | cut -d':' -f2 | sort -n | uniq -c | \
       tail -15 | sed -e 's/ *\([0-9]*\) *\([0-9]*\)/\2 \1/' | sort -n -r | \
       while read l; do printf "%6d %6d\n" $l; done ; \
    echo "=====================================" ) >>summary.txt

  generate_html >row.html

  cat summary.txt

  # Now create the archive of information
  rm -rf ${results_dir}
  mkdir ${results_dir}
  cp summary.txt report.txt sizes.txt configuration.txt \
     annotated.dmp hello.num row.html ${results_dir}
  cp ${COVBASE}/Explanations.txt.NotFound ${results_dir}
  echo "Results saved in ${results_dir}.tar.bz2"
  tar cjf ${results_dir}.tar.bz2 ${results_dir}
  rm -rf ${results_dir}
}

# Now we are ready to start doing real work
start=`date`

# If necessary, clean up the RTEMS build and test run directories
if [ ${do_clean} = "yes" ] ; then
  echo "Cleaning before building"
  rm -rf ${BASEDIR}/b-${BSP}
  rm -rf ${BASEDIR}/${BSP}-tests
else
  echo "Skipping clean before building"
fi

# If they don't exist, create the RTEMS build and test run directories
test -d ${BASEDIR}/b-${BSP}     || mkdir ${BASEDIR}/b-${BSP}
test -d ${BASEDIR}/${BSP}-tests || mkdir ${BASEDIR}/${BSP}-tests

# If requested, update and build the coverage support tools
if [ ${do_covmerge} = "yes" ] ; then
  echo "Updating and building covmerge..."

  cd ${COVBASE}
  check_status $? "cd covmerge"

  cvs up -Pd 2>&1 | grep -v ^cvs
  make clean all
  check_status $? "build covmerge"

  make
  check_status $? "make covmerge"
else
  echo "Skipping Updating and building covmerge..."
fi

# If requested, update the RTEMS tree
if [ ${do_rtems_update} = "yes" ] ; then
  echo "Updating RTEMS ..."
  cd ${RTEMSDIR}
  check_status $? "cd rtems"

  cvs up -Pd 2>&1 | grep -v ^cvs
  ./bootstrap -c
  ./bootstrap
else
  echo "Skipping Updating RTEMS ..."
fi

# Now let's patch the make/custom file
custom=${RTEMSDIR}/make/custom/${BSP}.cfg
if [ ! -r ${custom} ] ; then
  echo "Unable to read ${custom}"
  exit 1
fi

grep "^CFLAGS_OPTIMIZE_V.*=.*-O[2s]" ${custom} >/dev/null
if [ $? -ne 0 ] ; then
  echo "Unable to file CFLAGS_OPTIMIZE_V in ${custom}"
  exit 1
fi

sed -e "s/-O[2s]/${c_opt}/" <${custom} >/tmp/XXX
mv /tmp/XXX ${custom}

# If requested, configure RTEMS
if [ ${do_rtems_configure} = "yes" ] ; then
  echo "Configuring RTEMS..."
  rm -rf ${BASEDIR}/b-${BSP}/
  mkdir ${BASEDIR}/b-${BSP}/
  cd ${BASEDIR}/b-${BSP}/
  check_status $? "cd b-${BSP}"

  ##################
  ################## WARNING!!!!!!
  ##################
  ################## BE CAREFUL ABOUT THIS CONFIGURE COMMAND.  IT IS
  ################## VERY SPECIFIC TO COVERAGE TESTING
  ##################
  if [ ${do_posix} = "yes" ] ; then
    posix_en=en
  else
    posix_en=dis
  fi

  if [ ${do_developmental} = "yes" ] ; then
    EXPERIMENTAL_ARG="experimental"
  else
    EXPERIMENTAL_ARG="yes"
  fi

  ${RTEMSDIR}/configure NDEBUG=1 \
    RTEMS_DO_NOT_INLINE_THREAD_ENABLE_DISPATCH=1 \
    RTEMS_DO_NOT_INLINE_CORE_MUTEX_SEIZE=1 \
    RTEMS_DO_NOT_UNROLL_THREADQ_ENQUEUE_PRIORITY=1 \
    ${RTEMS_EXTRA_ARGS} \
    --target=${TARGET} --enable-rtemsbsp=${BSP} \
    --enable-maintainer-mode \
    --enable-coverage=${EXPERIMENTAL_ARG} \
    --disable-itron --${posix_en}able-posix --enable-tests \
    --disable-tcpip --disable-ada --disable-cxx \
    --prefix=${BASEDIR}/coverage/install >c.log 2>&1
  check_status $? "configuring RTEMS for ${BSP}"
else
  echo "Skipping Configuring RTEMS ..."
fi

# If requested, build RTEMS
if [ ${do_rtems_build} = "yes" ] ; then
  echo "Building RTEMS..."

  cd ${BASEDIR}/b-${BSP}/
  check_status $? "cd b-${BSP}"

  make -j4 >b.log 2>&1
  check_status $? "Building RTEMS for ${BSP}"
else
  echo "Skipping Building RTEMS ..."
fi

# If requested, copy the tests from the build tree to the run tree
if [ ${do_copy_tests} = "yes" ] ; then
  echo "Copying tests..."

  # clean destination
  rm -rf ${BASEDIR}/${BSP}-tests/*
  check_status $? "clean test directory"

  cd ${BASEDIR}/b-${BSP}/
  check_status $? "cd b-${BSP}"

  cp `find . -name *.exe` ../${BSP}-tests
else
  echo "Skipping copying tests..."
fi

# If requested, run the tests with coverage reporting enabled
if [ ${do_run_tests} = "yes" ] ; then
  echo "Running tests..."
  cd ${BASEDIR}/${BSP}-tests/
  check_status $? "cd ${BSP}-tests"

  time ${RUNNER} -c *.exe
else
  echo "Skipping Running tests..."
fi

# If requested, generate the coverage report
if [ ${do_report} = "yes" ] ; then
  echo "Generating report..."

  # Generate the configuration settings file
  ( \
    echo "#"
    echo "#  Settings for this coverage test run"
    echo "#"
    echo
    echo "Compiler version:   " `${TARGET}-gcc --version  | grep gcc`
    echo "Optimization flag   " ${c_opt}
    print_verbose
  ) > ${BASEDIR}/${BSP}-tests/configuration.txt

  cd ${BASEDIR}/${BSP}-tests/
  check_status $? "cd ${BSP}-tests"

  generate_report ${TARGET} ${BSP} ${COVERAGE_FORMAT}
else
  echo "Skipping Generating report..."
fi

stop=`date`

echo "Started: " ${start}
echo "Stopped: " ${stop}

exit 0

