#! /bin/sh
#
#  Script to generate coverage report
#
#  $Id$
#

vfile=`dirname $0`/VERSIONS-COVERAGE
if [ ! -r ${vfile} ] ; then
  echo VERSIONS-COVERAGE file not found
  exit 1
fi

source ${vfile}

if [ ! -d ${BASEDIR} ] ; then
  echo Have you set the BASEDIR in VERSIONS correctly?
  exit 1
fi

progname=${0##*/}        # fast basename hack for ksh, bash

if [ $# -ne 1 ] ; then
  echo Usage: ${0} TARGET
  exit 1
fi

#
#  Checks the status returned by executables and exits if it is non-zero.
#
check_fatal()
{
  if [ $1 -ne 0 ] ; then
    shift
    echo "ERROR: $*" >&2
    exit 1
  fi
}

NM=${1}-nm
type ${NM}
check_fatal $? "Cannot find ${NM} on PATH"

cd ${BASEDIR}/${BSP}-tests/
check_fatal $? "cd ${BSP}-tests"

${NM} -g -n hello.exe >hello.num

# Basic validity checking 
tlow=`grep "T ${lowsym}$" hello.num | cut -d' ' -f1`
if [ X${tlow} = X ] ; then
  echo "low symbol (${lowsym}) not found"
fi
thigh=`grep "T ${highsym}$" hello.num | cut -d' ' -f1`
if [ X${thigh} = X ] ; then
  echo "high symbol (${highsym}) not found"
fi

if [ X${tlow} = X -o X${thigh} = X ] ; then
  echo "Did you patch RTEMS for coverage testing?"
  exit 1
fi

rm -f merged.cov report.txt

( ${COVBASE}/covmerge -l 0x${tlow} -h 0x${thigh} -r report.txt \
    -E ${COVBASE}/Explanations.txt -f ${COVERAGE_FORMAT} \
    -T ${TARGET} -e hello.exe -m merged.cov *.cov; \
  echo "====== 15 Largest Range Sizes ======" ; \
  grep ^Size report | cut -d':' -f2 | sort -n | uniq -c | tail -15 ; 
  echo "=====================================" ) >summary.txt

cat summary.txt

tar cjf ${BSP}-`date +%Y%m%d-%H%M`.tar.bz2 summary.txt report.txt annotated.dmp

exit 0
