#! /bin/sh
#
#  Script to generate coverage report
#
#  Usage: TARGET BSP COVERAGE_FORMAT
#
#  $Id$
#

vfile=`dirname $0`/VERSIONS-COVERAGE
if [ ! -r ${vfile} ] ; then
  echo VERSIONS-COVERAGE file not found
  exit 1
fi

source ${vfile}

if [ ! -d ${BASEDIR} ] ; then
  echo Have you set the BASEDIR in VERSIONS correctly?
  exit 1
fi

progname=${0##*/}        # fast basename hack for ksh, bash

if [ $# -ne 3 ] ; then
  echo Usage: ${0} TARGET BSP COVERAGE_FORMAT
  exit 1
fi

TARGET=${1}
BSP=${2}
COVERAGE_FORMAT=${3}

#
#  Checks the status returned by executables and exits if it is non-zero.
#
check_fatal()
{
  if [ $1 -ne 0 ] ; then
    shift
    echo "ERROR: $*" >&2
    exit 1
  fi
}

# Check that tests ended successfully
check_endof()
{
  if [ -d log ] ; then
    logdir=log/
  else
    logdir=
  fi

  someFails=no
  while :
  do
    for f in `ls -1 ${logdir}* | grep -v info$`
    do
      case $f in
        # we don't expect an "END OF" from these
        *ppd*) ;;
        *fatal*) ;;
        *stackchk*) ;;
        *)
          grep "END OF" $f >/dev/null
          if [ $? -ne 0 ] ; then
            echo "WARNING - $f did not appear to complete execution"
            someFails=yes
          fi
          ;;
      esac
    done

    if [ X${1} = X ] ; then
      break
    fi
    sleep $1
    echo
  done
  if [ ${someFails} = yes ] ; then
    echo "WARNING - Results may not be accurate"
  fi
}

# Start real action
NM=${TARGET}-nm
type ${NM}
check_fatal $? "Cannot find ${NM} on PATH"

cd ${BASEDIR}/${BSP}-tests/
check_fatal $? "cd ${BSP}-tests"

${NM} -g -n hello.exe >hello.num

# Basic validity checking 
tlow=`grep "T ${lowsym}$" hello.num | cut -d' ' -f1`
if [ X${tlow} = X ] ; then
  echo "low symbol (${lowsym}) not found"
fi
thigh=`grep "T ${highsym}$" hello.num | cut -d' ' -f1`
if [ X${thigh} = X ] ; then
  echo "high symbol (${highsym}) not found"
fi

if [ X${tlow} = X -o X${thigh} = X ] ; then
  echo "Did you patch RTEMS for coverage testing?"
  exit 1
fi

rm -f merged.cov report.txt

( \
  check_endof; \
  ${COVBASE}/covmerge -l 0x${tlow} -h 0x${thigh} -r report.txt \
    -s sizes.txt \
    -E ${COVBASE}/Explanations.txt -f ${COVERAGE_FORMAT} \
    -T ${TARGET} -e hello.exe -m merged.cov *.cov; \
  echo "====== 15 Largest Range Sizes ======" ; \
  grep ^Size report.txt | cut -d':' -f2 | sort -n | uniq -c | tail -15 ; 
  echo "=====================================" ) >summary.txt

cat summary.txt

# Now create the archive of information
dated=${BSP}-`date +%Y%m%d-%H%M`
rm -rf ${dated}
mkdir ${dated}
cp summary.txt report.txt sizes.txt annotated.dmp ${dated}
cp ${COVBASE}/Explanations.txt.NotFound ${dated}
tar cjf ${dated}.tar.bz2 ${dated}
rm -rf ${dated}

exit 0
