#! /bin/bash
#
#  This script checks for the "END OF" message in all RTEMS tests.
#  It reports tests which do not appear to have completed successfully
#
#  $Id$
#

if [ -d log ] ; then
  logdir=log/
else
  logdir=
fi

while :
do
  for f in `ls -1 ${logdir}* | grep -v info$`
  do
    case $f in
      # we don't expect an "END OF" from these
      *ppd*) ;;
      *fatal*) ;;
      *minimum*) ;;
      *stackchk*) ;;
      # These do not know when they hit the case so run until killed.
      *spintrcritical06*) ;;
      *spintrcritical07*) ;;
      *spintrcritical09*) ;;
      *spintrcritical13*) ;;
      *spintrcritical14*) ;;
      *)
        grep "END OF" $f >/dev/null
        if [ $? -ne 0 ] ; then
          echo "WARNING - $f did not appear to complete execution"
          someFails=yes
        fi
        ;;
    esac
  done

  if [ X${1} = X ] ; then
    break
  fi
  sleep $1
  echo
done
exit 0
