#
#  $Id$
#

INSTALL_DIR=../bin
GDBSIM_SCRIPTS=h8sim jmr3904 lm32_evr m32csim m32rsim psim sis simsh
SKYEYE_SCRIPTS=ant5206 bf537Stamp csb337 csb350 csb360 edb7312 ezkit533 \
  gumstix rtl22xx smdk2410 leon2-skyeye

TSIM_SCRIPTS=erc32 leon2 leon3
QEMU_SCRIPTS=qemu-rtems qemu-leon2 qemu-uc5282
OTHER_SCRIPTS=avrtest
GENERATED_SCRIPTS=\
  ${GDBSIM_SCRIPTS} $(GDBSIM_SCRIPTS:%=%-gdb) \
  ${SKYEYE_SCRIPTS} $(SKYEYE_SCRIPTS:%=%-gdb) \
  ${TSIM_SCRIPTS} $(TSIM_SCRIPTS:%=%-gdb) \
  ${QEMU_SCRIPTS} ${OTHER_SCRIPTS}

COMPILED_PROGRAMS=usleep
UNPROCESSED_SCRIPTS=nosim check_endof \
  rtems-gdb-macros-4.7 rtems-gdb-macros-4.8 rtems-gdb-macros-4.9 \
  rtems-gdb-macros-4.10

all: prep ${GENERATED_SCRIPTS} ${COMPILED_PROGRAMS} \
     ${UNPROCESSED_SCRIPTS} install

prep:
	test -d ${INSTALL_DIR} || mkdir ${INSTALL_DIR}

usleep: usleep.c
	$(CC) -o $@ $<

### QEMU BSPs
qemu-rtems: gdb-sim-run.in qemu-rtems.in
	./mkrun no i386 i386 qemu-rtems

qemu-leon2: gdb-sim-run.in qemu-leon2.in
	./mkrun no SPARC sparc qemu-leon2

qemu-uc5282: gdb-sim-run.in qemu-uc5282.in
	./mkrun no M68K-Coldfire m68k qemu-uc5282

### Skyeye Simulator BSPs
ant5206: gdb-sim-run.in gdb-sim.in ant5206.in
	./mkrun yes M68K-Coldfire m68k ant5206

csb337: gdb-sim-run.in gdb-sim.in csb337.in
	./mkrun yes ARM arm csb337

csb350: gdb-sim-run.in gdb-sim.in csb350.in
	./mkrun yes MIPS mips csb350

csb360: gdb-sim-run.in gdb-sim.in csb360.in
	./mkrun yes M68K-Coldfire m68k csb360

bf537Stamp: gdb-sim-run.in gdb-sim.in bf537Stamp.in
	./mkrun yes Blackfin bfin bf537Stamp

edb7312: gdb-sim-run.in gdb-sim.in edb7312.in
	./mkrun yes ARM arm edb7312

gumstix: gdb-sim-run.in gdb-sim.in gumstix.in
	./mkrun yes ARM arm gumstix

rtl22xx: gdb-sim-run.in gdb-sim.in rtl22xx.in
	./mkrun yes ARM arm rtl22xx

smdk2410: gdb-sim-run.in gdb-sim.in smdk2410.in
	./mkrun yes ARM arm smdk2410

ezkit533: gdb-sim-run.in gdb-sim.in ezkit533.in
	./mkrun yes Blackfin bfin ezkit533

leon2-skyeye: gdb-sim-run.in gdb-sim.in leon2-skyeye.in
	./mkrun yes SPARC sparc leon2-skyeye

### TSIM Simulator BSPs
erc32: gdb-sim-run.in gdb-sim.in erc32.in tsim-support
	./mkrun yes SPARC sparc erc32

leon2: gdb-sim-run.in gdb-sim.in leon2.in tsim-support
	./mkrun yes SPARC sparc leon2

leon3: gdb-sim-run.in gdb-sim.in leon3.in tsim-support
	./mkrun yes SPARC sparc leon3

### GDB Simulator BSPs
h8sim h8sim-gdb: gdb-sim-run.in gdb-sim.in h8sim.in
	./mkrun yes H8300 h8300 h8sim

jmr3904 jmr3904-gdb: gdb-sim-run.in gdb-sim.in jmr3904.in
	./mkrun yes MIPS mipstx39 jmr3904

lm32_evr lm32_evr-gdb: gdb-sim-run.in gdb-sim.in lm32_evr.in
	./mkrun yes LM32 lm32 lm32_evr

m32csim m32csim-gdb: gdb-sim-run.in gdb-sim.in m32csim.in
	./mkrun yes M32C m32c m32csim

m32rsim m32rsim-gdb: gdb-sim-run.in gdb-sim.in m32rsim.in
	./mkrun yes M32R m32r m32rsim

psim psim-gdb: gdb-sim-run.in gdb-sim.in psim.in
	./mkrun yes PowerPC powerpc psim

sis sis-gdb: gdb-sim-run.in gdb-sim.in sis.in
	./mkrun yes SPARC sparc sis

simsh simsh-gdb: gdb-sim-run.in gdb-sim.in simsh.in
	./mkrun yes SuperH sh simsh

## AVR Test (uses Simulavrxx)
avrtest: gdb-sim-run.in avrtest.in
	./mkrun no AVR avr avrtest

clean:
	rm -f ${GENERATED_SCRIPTS} ${COMPILED_PROGRAMS}

install:
	for i in ${GENERATED_SCRIPTS} ${COMPILED_PROGRAMS} \
                 ${UNPROCESSED_SCRIPTS} ; do \
	  cp $${i} ${INSTALL_DIR}/$${i} ; \
	  chmod +x ${INSTALL_DIR}/$${i} ; \
	done

