#! /bin/sh
#
#  Helper to sed run scripts
#

doGdb=$1
CPU=$2
CPU_TARGET=$3
BSP=$4
RUN=${BSP}
GDB=${BSP}-gdb

# Generate RUN script
cat gdb-sim-run.in | \
  sed -e "s/@CPU@/${CPU}/" \
      -e "s/@CPU_TARGET@/${CPU_TARGET}/" \
      -e "s/@BSP@/${BSP}/" \
      -e "/^##INSERT BSP SUPPORT HERE/r ${BSP}.in" | \
  sed -e "/^##INSERT SKYEYE SUPPORT HERE/r skyeye-support" \
      -e "/^##INSERT TSIM SUPPORT HERE/r tsim-support" >${RUN}
chmod +x ${RUN}

# Generate GDB script
if [ ${doGdb} = yes ] ; then
  cat gdb-sim.in | \
    sed -e "s/@CPU@/${CPU}/" \
	-e "s/@CPU_TARGET@/${CPU_TARGET}/" \
	-e "s/@BSP@/${BSP}/" \
	-e "/^##INSERT BSP SUPPORT HERE/r ${BSP}.in" | \
    sed -e "/^##INSERT SKYEYE SUPPORT HERE/r skyeye-support" \
        -e "/^##INSERT TSIM SUPPORT HERE/r tsim-support" >${GDB}
  chmod +x ${GDB}
fi

exit 0
