#! /bin/sh

if [ ! -r ChangeLog ] ; then
  echo "ERROR: No ChangeLog in current directory."
  exit 1
fi

cvs diff -u ChangeLog| grep  ^+ | \
  sed -e '/^+++/d' -e 's/^+ //' -e 's/^+//' >ch
cat ch

cvs commit -F ch
rm -f ch
exit 0
